### PR TITLE
Localized/Customized button text

### PR DESCRIPTION
**Pull request by Uscher1**
Currently the buttons 'Save' and 'Discard' in the crop view have a fixed text in English only. Following builder functions allow to customize the text of these buttons.
```
CropImageIntentBuilder cropImage = new CropImageIntentBuilder(200, 200, m_tempImageUri);
cropImage.setButtonTextSave(getResources().getString(R.string.button_save));
cropImage.setButtonTextDiscard(getResources().getString(R.string.button_discard));
```

### CODE REVIEW

**Comment by lvillani** [comment]
Can't you overwrite the `crop_save_text` and `crop_save_discard` string resources in your project?

**Comment by Uscher1** [comment]
No. CropImage behaves like a separate app with its own string resources and you cannot overwrite strings of another app. In addition the button has a fixed width which is too small for translated text. I also have adjusted this. 

Localization is a must requirement. It is not possible to integrate translations for all languages. But builder functions do the job.

**Comment by lvillani** [comment]
I'm kind of busy these days, I hope to be able to review this PR this week-end.

**Comment by lvillani** [comment]
In my tests, overriding `crop_save_text` and `crop_save_discard` in the containing project works just fine. As for the button sizes, they should probably be extracted to a dimension resource (e.g.: `crop_save_button_width` and `crop_discard_button_width` so that they can be overridden as well, instead of swapping one hard-coded value for another. Even better would probably be to create a style, but I find them overkill in this particular case.

**Comment by Uscher1** [comment]
You are right. The app string can override the library string:

> In the cases where a resource ID is defined in both the application and the library, the tools ensure that the resource declared in the application gets priority and that the resource in the library project is not compiled into the application .apk.

So there is just to improve the button layout. The buttons should have the same width in order to have a nice look. I think it is really good enough just to enlarge the button width. You may just take over the layout file cropimage.xml. I tested it with some languages and it's fine.

**Comment by lvillani** [comment]
I just pushed v1.1.2 that adds `@dimen/crop_button_width` ([patch](https://github.com/lvillani/android-cropimage/commit/15d08a1a0fe6b3188e616b864a4ff94914dcbac1)) that you can override in your app. The default is `120dp`. Does that work for you?

**Comment by Uscher1** [comment]
Good solution. Default value is fine and text & width can be overridden. Thank you.

**Comment by lvillani** [comment]
OK, I'm closing this PR then.

**Pull request closed without merging**
